[package]
name = "jtable"
version = "0.1.0"
authors = ["filsam <samoylovfp@gmail.com>"]
description = "Utility classes to easily render json responses for jtable.org plugin"
license = "Apache-2.0"

[dependencies]
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
